import { Button } from "@/components/ui/button";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GuestLayout({ children }) {
  return (
    <div>
      <div className="w-full bg-[#1300E1] text-white rounded-full pl-4 flex gap-2 items-center min-h-10">
        <h4 className="flex-1 text-center"><Link href="/">Browsewipe Registeration</Link></h4>
        <div className="py-2 bg-white rounded-e-full">
          <Button variant="link" className="text-[#1300E1]"><Link href="#">Download App</Link></Button>
          <Button variant="link" className="text-[#1300E1]"><Link href="#">Download Extension</Link></Button>
        </div>
      </div>
      <main className="py-5 md:py-20">
        {children}
      </main>
    </div>
  );
}
